# Generated by Django 5.1.15 on 2026-06-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_ai_limit', models.PositiveIntegerField(default=3, help_text='Number of AI explanations an anonymous visitor can unlock.')),
                ('free_ai_limit', models.PositiveIntegerField(default=5, help_text='Total AI explanations a logged-in free user can unlock.')),
                ('words_per_set', models.PositiveIntegerField(default=30, help_text='Target number of words per word set / chunk.')),
            ],
            options={
                'verbose_name': 'Site setting',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
