# Generated by Django 5.1.15 on 2026-06-11 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('simple_definition', models.TextField()),
                ('example_sentence', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('advanced', 'Advanced')], max_length=20)),
                ('is_demo', models.BooleanField(default=False, help_text='Demo words can be AI-explained by anonymous visitors.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('word_set', 'text'),
            },
        ),
        migrations.CreateModel(
            name='ExampleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, help_text='Optional list of MCQ options.', null=True)),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('gre', 'GRE'), ('bd_govt', 'BD Govt Exam'), ('other', 'Other')], default='other', max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_questions', to='vocabulary.word')),
            ],
        ),
        migrations.CreateModel(
            name='AIExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_explanation', to='vocabulary.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('advanced', 'Advanced')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_sets', to='vocabulary.category')),
            ],
            options={
                'ordering': ('category', 'level', 'order'),
                'unique_together': {('category', 'level', 'order')},
            },
        ),
        migrations.AddField(
            model_name='word',
            name='word_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.wordset'),
        ),
    ]
